service: DeepLearningPipeline

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  region: us-east-1
  runtime: python3.6
  memorySize: 1536
  timeout: 30
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:ListBucket"
       Resource:
         - arn:aws:s3:::serverlessdeeplearning
    -  Effect: "Allow"
       Action:
         - "s3:GetObject"
       Resource:
         - arn:aws:s3:::serverlessdeeplearning/*
    -  Effect: "Allow"
       Action:
         - "sqs:ReceiveMessage"
         - "sqs:DeleteMessage"
         - "sqs:GetQueueAttributes"
       Resource:
         - arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:DLReadSQS
    -  Effect: "Allow"
       Action:
         - "sqs:SendMessage"
         - "sqs:GetQueueUrl"
       Resource:
         - arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:DLWriteSQS

package:
  exclude:
    - node_modules/**

functions:
  main:
    handler: index.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - DLReadSQS
              - Arn

resources:
  Resources:  
    DLWriteSQS:   
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "DLWriteSQS"
    DLReadSQS:   
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "DLReadSQS"

plugins:
  - serverless-pseudo-parameters